### ISSUE TITLE
About link activation

### ISSUE THREAD

**Issue by thegurf** [iluaepidi/rating-tool#8]
The about link/modal can't be activated by keyboard or from Chromevox.

**Comment by p-sl** [comment]
The link can be activadted normally like any other links. Once link is focused pressing enter key will activate the link. Tested keyboard navigation in most of browsers.

**Comment by thegurf** [comment]
I spent some more time testing this today. The issue is with the ChromeVox browser extensions. When that is enabled, tabbing to the link and pressing enter on "About" moves focus to the footer without opening the modal. Looks like holding down the ChromeVox key when activating the control does work, but the interaction is different than every other link on the page in that scenario. 

Will do some additional testing with other AT and see if I can get to the bottom of why.

**Comment by thegurf** [comment]
Closing as this module is no longer in use.
